export const $ = (selector, root = document) => root.querySelector(selector);

export function cacheDom() {
  return {
    appEl: $("#app"),
    statusEl: $("#status"),
    statusDetailEl: $("#statusDetail"),
    themeToggle: $("#themeToggle"),
    reconnectBtn: $("#reconnectBtn"),
    disconnectBtn: $("#disconnectBtn"),
    resetLayoutBtn: $("#resetLayoutBtn"),
    connectionForm: $("#connectionForm"),
    wsUrlInput: $("#wsUrlInput"),
    subprotocolInput: $("#subprotocolInput"),
    nickInput: $("#nickInput"),
    applyNickBtn: $("#applyNickBtn"),
    metricGrid: $("#metricGrid"),
    usersEl: $("#users"),
    userCountEl: $("#userCount"),
    timelineEl: $("#timeline"),
    clearTimelineBtn: $("#clearTimelineBtn"),
    composerForm: $("#composerForm"),
    composerMode: $("#composerMode"),
    composerInput: $("#composerInput"),
    composerHelp: $("#composerHelp"),
    composerCount: $("#composerCount"),
    sampleJsonBtn: $("#sampleJsonBtn"),
    clearComposerBtn: $("#clearComposerBtn"),
    presetButtons: $("#presetButtons"),
    featureList: $("#featureList"),
    commandList: $("#commandList"),
    frameList: $("#frameList"),
    clearFramesBtn: $("#clearFramesBtn"),
    socketUrlEl: $("#socketUrl"),
    socketProtocolEl: $("#socketProtocol"),
    connectionIdEl: $("#connectionId"),
    lastSequenceEl: $("#lastSequence"),
    peerAddressEl: $("#peerAddress"),
    pingIntervalEl: $("#pingInterval"),
    missedPongsEl: $("#missedPongs"),
    maxMessageSizeEl: $("#maxMessageSize"),
    dashboardEl: $("#dashboard"),
    panelHeads: Array.from(document.querySelectorAll(".dashboard-block .panel-head")),
    themeColorMeta: document.querySelector('meta[name="theme-color"]'),
  };
}